liderpythondjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('modulos.users.urls', 'users'), namespace='users'))
]

modulos/users/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .views import Login, Panel, exit
from .views import Rus, LisMun, RegMun, UpdMun, DelMun, LisReg, RegReg, UpdReg, DelReg
from .views import ApiLogin, ApiRus, ApiLisMun, ApiRegMun, ApiUpdMun, ApiDelMun, MunicipioDetail
from .views import ApiLisReg, ApiRegReg, ApiUpdReg, ApiDelReg, RegionDetail, ApiLogout, LogicaRespuesta

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('salir/', exit, name='salir'),
    path('start/',
         login_required(Panel.as_view(), login_url=reverse_lazy('users:login')), name='base'),
    path('reg/usu/', login_required(Rus.as_view(), login_url=reverse_lazy('users:login')), name='rus'),
    # Municipios
    path('lis/mun/', login_required(LisMun.as_view(), login_url=reverse_lazy('users:login')), name='lis_mun'),
    path('reg/mun/', login_required(RegMun.as_view(), login_url=reverse_lazy('users:login')), name='reg_mun'),
    path('upd/<int:pk>/mun/', login_required(UpdMun.as_view(), login_url=reverse_lazy('users:login')), name='upd_mun'),
    path('del/<int:pk>/mun/', login_required(DelMun.as_view(), login_url=reverse_lazy('users:login')), name='del_mun'),
    # Regiones
    path('lis/reg/', login_required(LisReg.as_view(), login_url=reverse_lazy('users:login')), name='lis_reg'),
    path('reg/reg/', login_required(RegReg.as_view(), login_url=reverse_lazy('users:login')), name='reg_reg'),
    path('upd/<int:pk>/reg/', login_required(UpdReg.as_view(), login_url=reverse_lazy('users:login')), name='upd_reg'),
    path('del/<int:pk>/reg/', login_required(DelReg.as_view(), login_url=reverse_lazy('users:login')), name='del_reg'),

    # RESTful API
    path('restfulapi/login/', ApiLogin.as_view()),
    path('restfulapi/salir/', ApiLogout.as_view()),
    path(r'restfulapi/reg/usu/', ApiRus.as_view()),
    # Municipio
    path('restfulapi/lis/mun/', ApiLisMun.as_view()),
    path('restfulapi/reg/mun/', ApiRegMun.as_view()),
    path('restfulapi/upd/<int:pk>/mun/', ApiUpdMun.as_view()),
    path('restfulapi/del/<int:pk>/mun/', ApiDelMun.as_view()),
    path('restfulapi/det/<int:pk>/mun/', MunicipioDetail.as_view()),
    # Region
    path('restfulapi/lis/reg/', ApiLisReg.as_view()),
    path('restfulapi/reg/reg/', ApiRegReg.as_view()),
    path('restfulapi/upd/<int:pk>/reg/', ApiUpdReg.as_view()),
    path('restfulapi/del/<int:pk>/reg/', ApiDelReg.as_view()),
    path('restfulapi/det/<int:pk>/reg/', RegionDetail.as_view()),
    # LOGICA
    path('logica/<int:entrada>/respuesta/', LogicaRespuesta.as_view()),
]

templates/del.html
{% extends "base.html" %}
{% block tit_cont %}{{ tit_cont }}{% endblock %}
{% block sub_tit_cont %}{{ sub_tit_cont }}{% endblock %}
{% block script %}
    <script type="text/javascript">
        $('#button-id-cancel').on('click', function (e) {
            e.preventDefault();
            window.history.back();
        });
    </script>
{% endblock script %}
{% block contenido %}
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-12 col-lg-6 col-md-6 col-12">
                <div class="card pull-up">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <h4 class="card-title">{{ tit_cont }} {{ sub_tit_cont }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card pull-up">
            <div class="card-body">
                    <form id="masivo" class="form-horizontal" action="." method="POST">
                    {% csrf_token %}

                    <div class="card-action no-border text-center">
                        {% if mensaje %}
                            <span style="color: #2D3945">{{ mensaje }}</span>
                        {% else %}
                            <span style="color: #2D3945;"><b>SE ENCUENTRA SEGURO DE ELIMINAR ESTE REGISTRO: {{ object }}</b></span>
                        {% endif %}
                    </div>
                    <br>
                    <br>
                    <div class="card-action no-border text-center">
                        <input name="submit" value="Enviar" class="btn btn-primary"
                               id="submit-id-submit" type="submit">

                        <input name="cancel" value="Cancel" class="btn btn-default" id="button-id-cancel"
                               autocomplete="off" type="button">
                    </div>
                    </form>
                </div>
        </div>
    </div>
{% endblock contenido %}

templates/formadmin.html
{% extends 'base.html' %}
{% load crispy_forms_tags humanize %}
{% block tit_cont %}{{ tit_cont }}{% endblock %}
{% block sub_tit_cont %}{{ sub_tit_cont }}{% endblock %}
{% block contenido %}
    <div class="content-wrapper">
        <div class="row">
            <div class="col-xl-12 col-lg-6 col-md-6 col-12">
                <div class="card pull-up">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <h4 class="card-title">{{ tit_cont }} {{ sub_tit_cont }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card pull-up">
            <div class="card-body">
                {% if form.is_multipart %}
                    <form id="masivo" class="form form-horizontal" role="form" enctype="multipart/form-data"
                          method="POST" action=".">
                {% else %}
                    <form class="form form-horizontal" role="form" method="POST" action=".">
                {% endif %}
                {% csrf_token %}
                <div class="form-body">
                    {% crispy form %}
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contenido %}
{% block estilos %}
    <link rel="stylesheet" type="text/css"
          href="{{ STATIC_URL }}login/css/bootstrap-duallistbox.min.css">
{% endblock estilos %}
{% block script %}
    <script src="{{ STATIC_URL }}login/js/jquery.bootstrap-duallistbox.min.js"></script>
    <script>
        $('.selectmultiple').bootstrapDualListbox();
        $('#button-id-cancel').on('click', function (e) {
            e.preventDefault();
            window.history.back();
        });
    </script>
{% endblock script %}

templates/inicio.html
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>LOGIN - TEST</title>
    <link rel="apple-touch-icon" href="{{ STATIC_URL }}apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="{{ STATIC_URL }}favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/vendors.min.css">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/colors.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/components.css">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/login-register.css">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}login/css/style.css">
    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu 1-column  bg-full-screen-image blank-page" data-open="click" data-menu="vertical-menu" data-col="1-column">
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row mb-1">
            </div>
            <div class="content-body">
                <section class="flexbox-container">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="col-lg-4 col-md-8 col-10 box-shadow-2 p-0">
                            <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                                <div class="card-header border-0">
                                    <div class="card-title text-center">
                                        <img src="{{ STATIC_URL }}logo-dark.png" alt="branding logo">
                                    </div>
                                    <h6 class="card-subtitle line-on-side text-muted text-center font-small-3 pt-2"><span>Login</span></h6>
                                </div>
                                <div class="card-content">
                                    <div class="card-body">
                                        <form class="form-horizontal" action="{% url 'users:login' %}" novalidate method="post">
                                            {% csrf_token %}
                                            <fieldset class="form-group position-relative has-icon-left">
                                                <input type="text" class="form-control" id="user-name" placeholder="Your Username" required name="usu">
                                                <div class="form-control-position">
                                                    <i class="ft-user"></i>
                                                </div>
                                            </fieldset>
                                            <fieldset class="form-group position-relative has-icon-left">
                                                <input type="password" class="form-control" id="user-password" placeholder="Enter Password" required name="passwd">
                                                <div class="form-control-position">
                                                    <i class="la la-key"></i>
                                                </div>
                                            </fieldset>
                                            <button type="submit" class="btn btn-outline-info btn-block"><i class="ft-unlock"></i> Login</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
    <!-- END: Content-->


    <!-- BEGIN: Vendor JS-->
    <script src="{{ STATIC_URL }}login/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="{{ STATIC_URL }}login/js/jqBootstrapValidation.js"></script>
    <!-- END: Page Vendor JS-->
    <script src="{{ STATIC_URL }}login/js/toastr.min.js" type="text/javascript"></script>
    <!-- BEGIN: Theme JS-->
    <script src="{{ STATIC_URL }}login/js/app-menu.js"></script>
    <script src="{{ STATIC_URL }}login/js/app.js"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <script src="{{ STATIC_URL }}login/js/form-login-register.js"></script>
    <!-- END: Page JS-->

</body>
<!-- END: Body-->

</html>

templates/menuadmin.html
{% if request.user.is_superuser %}
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
        <li class="active"><a href="{% url 'users:base' %}"><i class="la la-home"></i>
            <span class="menu-title" data-i18n="">Administrativo</span></a>
        </li>
        <li class=" navigation-header">
            <span data-i18n="nav.category.professional">Menu</span>
            <i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Menu">
            </i>
        </li>

        <li class=" menu-item"><a href="{% url 'users:rus' %}">
            <i class="la la-users"></i>
            <span class="menu-title" data-i18n="">Create user</span>
        </a>

        </li>
        <li class=" menu-item"><a href="{% url 'users:lis_mun' %}">
            <i class="la la-bookmark"></i>
            <span class="menu-title" data-i18n="">Municipios</span>
        </a>
        </li>
        <li class=" menu-item"><a href="{% url 'users:lis_reg' %}">
            <i class="la la-globe"></i>
            <span class="menu-title" data-i18n="">Regiones</span>
        </a>
        </li>
    </ul>
{% endif %}