liderpythondjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('modulos.users.urls', 'users'), namespace='users'))
]

modulos/users/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .views import Login, Panel, exit
from .views import Rus, LisMun, RegMun, UpdMun, DelMun, LisReg, RegReg, UpdReg, DelReg
from .views import ApiLogin, ApiRus, ApiLisMun, ApiRegMun, ApiUpdMun, ApiDelMun, MunicipioDetail
from .views import ApiLisReg, ApiRegReg, ApiUpdReg, ApiDelReg, RegionDetail, ApiLogout, LogicaRespuesta

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('salir/', exit, name='salir'),
    path('start/',
         login_required(Panel.as_view(), login_url=reverse_lazy('users:login')), name='base'),
    path('reg/usu/', login_required(Rus.as_view(), login_url=reverse_lazy('users:login')), name='rus'),
    # Municipios
    path('lis/mun/', login_required(LisMun.as_view(), login_url=reverse_lazy('users:login')), name='lis_mun'),
    path('reg/mun/', login_required(RegMun.as_view(), login_url=reverse_lazy('users:login')), name='reg_mun'),
    path('upd/<int:pk>/mun/', login_required(UpdMun.as_view(), login_url=reverse_lazy('users:login')), name='upd_mun'),
    path('del/<int:pk>/mun/', login_required(DelMun.as_view(), login_url=reverse_lazy('users:login')), name='del_mun'),
    # Regiones
    path('lis/reg/', login_required(LisReg.as_view(), login_url=reverse_lazy('users:login')), name='lis_reg'),
    path('reg/reg/', login_required(RegReg.as_view(), login_url=reverse_lazy('users:login')), name='reg_reg'),
    path('upd/<int:pk>/reg/', login_required(UpdReg.as_view(), login_url=reverse_lazy('users:login')), name='upd_reg'),
    path('del/<int:pk>/reg/', login_required(DelReg.as_view(), login_url=reverse_lazy('users:login')), name='del_reg'),

    # RESTful API
    path('restfulapi/login/', ApiLogin.as_view()),
    path('restfulapi/salir/', ApiLogout.as_view()),
    path(r'restfulapi/reg/usu/', ApiRus.as_view()),
    # Municipio
    path('restfulapi/lis/mun/', ApiLisMun.as_view()),
    path('restfulapi/reg/mun/', ApiRegMun.as_view()),
    path('restfulapi/upd/<int:pk>/mun/', ApiUpdMun.as_view()),
    path('restfulapi/del/<int:pk>/mun/', ApiDelMun.as_view()),
    path('restfulapi/det/<int:pk>/mun/', MunicipioDetail.as_view()),
    # Region
    path('restfulapi/lis/reg/', ApiLisReg.as_view()),
    path('restfulapi/reg/reg/', ApiRegReg.as_view()),
    path('restfulapi/upd/<int:pk>/reg/', ApiUpdReg.as_view()),
    path('restfulapi/del/<int:pk>/reg/', ApiDelReg.as_view()),
    path('restfulapi/det/<int:pk>/reg/', RegionDetail.as_view()),
    # LOGICA
    path('logica/<int:entrada>/respuesta/', LogicaRespuesta.as_view()),
]

templates/region/lis.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block tit_cont %}{{ tit_cont }}{% endblock %}
{% block sub_tit_cont %}{{ sub_tit_cont }}{% endblock %}
{% load humanize %}
{% block script %}

{% endblock script %}
{% block contenido %}
    <!-- PAGE CONTENT WRAPPER -->
    <div class="row">
        <div class="col-md-12">
            <!-- Configuration option table -->
        <section id="configuration">
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title">{{ tit_cont }} {{ sub_tit_cont }}</h4>
                  <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                  <div class="heading-elements">
                    <ul class="list-inline mb-0">

                    </ul>
                  </div>

                </div>

                <div class="card-content collapse show">

                  <div class="card-body card-dashboard">
                    <form class="form-inline" role="form" method="get" action="">
                        <div class="form-group">
                              <input type="text" class="form-control" placeholder="Nombre" value="{{ nom }}" name="nom"/>
                        </div>
                        <button type="submit" class="btn btn-icon btn-info mr-1"><i class="la la-search"></i></button>
                        <a href="{% url 'users:reg_reg' %}" class="btn btn-icon btn-success mr-1"  ><i class="ft-plus"></i>Crear</a>
                    </form>
                  <br><br>
                   {% if is_paginated %}
                    <div class="float-left">
                        <ul class="pager">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="ft-arrow-left"></i>Anterior</a></li>
                            {% endif %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">Siguiente<i class="ft-arrow-right"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>

                {% endif %}
                   <div class="table-responsive">
                    <table class="table  mb-0">
                      <thead>
                        <tr>
                          <th>Codigo</th>
                          <th>Nombre</th>
                          <th></th>
                         </tr>
                      </thead>
                      <tbody>

                      {% for lo in object_list %}

                        <tr>
                          <td>{{ lo.codigo }}</td>
                          <td>
                              {{ lo.nombre }}
                          </td>
                          <td>
                              <a href="{% url 'users:upd_reg' pk=lo.id %}" title="Editar"><i class="ft-edit text-success"></i></a>
                              <a href="{% url 'users:del_reg' pk=lo.id %}" title="Eliminar"><i class="ft-trash-2 ml-1 text-warning"></i></a>
                          </td>

                        </tr>
                         {% empty %}
                         <tr id="trow_1">
                            <td colspan="=20">No hay datos</td>
                         </tr>

                      {% endfor %}
                      </tbody>

                    </table>
                   </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </section>
        <!--/ Configuration option table -->
        </div>
    </div>
 {% endblock %}